apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: my-webapp-container
        image: chandanunix001/my-webapp:latest
        ports:
        - containerPort: 80
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
spec:
  type: NodePort    # or NodePort if using Minikube
  selector:
    app: my-webapp      # matches Deployment pod labels
  ports:
  - port: 80            # Service port
    targetPort: 80      # Pod container port
    

    
